name: cdk-github-actions-deploy
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Setup dependencies
        working-directory: aws
        run: npm ci
      - name: Copy prisma
        run: cp -R ./prisma ./aws/layer/prisma
      - name: Generate prisma client
        working-directory: aws/layer/prisma
        run: npx prisma generate
        env:
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      - name: Setup lambda & layer
        run: bash ./lamba-dependency.sh
      - name: CDK Deploy
        working-directory: aws
        run: npm run cdk deploy
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CHATGPT_APIKEY: ${{ secrets.CHATGPT_APIKEY }}
          DREAM_STUDIO_APIKEY: ${{ secrets.DREAM_STUDIO_APIKEY }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
